src/Entity/Enchere.php
<?php

namespace App\Entity;

use App\Repository\EnchereRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EnchereRepository::class)
 */
class Enchere
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $auction_value;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="encheres")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Annonce::class, inversedBy="encheres")
     * @ORM\JoinColumn(nullable=false)
     */
    private $annonce;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuctionValue(): ?float
    {
        return $this->auction_value;
    }

    public function setAuctionValue(float $auction_value): self
    {
        $this->auction_value = $auction_value;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getAnnonce(): ?Annonce
    {
        return $this->annonce;
    }

    public function setAnnonce(?Annonce $annonce): self
    {
        $this->annonce = $annonce;

        return $this;
    }
}

src/Form/EnchereType.php
<?php

namespace App\Form;

use App\Entity\Enchere;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EnchereType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('auction_value')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Enchere::class,
        ]);
    }
}

src/Controller/EnchereController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Annonce;
use App\Entity\Enchere;
use App\Form\EnchereType;
use App\Repository\UserRepository;
use App\Repository\AnnonceRepository;
use App\Repository\EnchereRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/encheres")
 */
class EnchereController extends AbstractController
{
    /**
     * @Route("/", name="enchere_index", methods={"GET"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function index(EnchereRepository $enchereRepository): Response
    {
        return $this->render('enchere/index.html.twig', [
            'encheres' => $enchereRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="enchere_new", methods={"GET","POST"})
     * @IsGranted("ROLE_USER")
     */
    public function new(Request $request, AnnonceRepository $annonceRepository): Response
    {   
        $enchere = new Enchere();
        $response = new Response();
        $user = $this->getUser();
        $annonce = $annonceRepository->findOneBy(['id'=>$request->query->get('annonce_id')]);

        $enchere->setAuctionValue($request->query->get('enchere_value'));
        $enchere->setUser($user);
        $enchere->setAnnonce($annonce);
        $enchere->setCreatedAt(new \DateTime('now'));
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($enchere);
        $entityManager->flush();

        $response->headers->set('content-type','application/json');
        $response->setContent(json_encode(['Statut'=>'Enchère ajoutée']));
        return $response;
    }

    /**
     * @Route("/{id}", name="enchere_show", methods={"GET"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function show(Enchere $enchere): Response
    {
        return $this->render('enchere/show.html.twig', [
            'enchere' => $enchere,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="enchere_edit", methods={"GET","POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $request, Enchere $enchere): Response
    {
        $form = $this->createForm(EnchereType::class, $enchere);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('enchere_index');
        }

        return $this->render('enchere/edit.html.twig', [
            'enchere' => $enchere,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="enchere_delete", methods={"DELETE"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $request, Enchere $enchere): Response
    {
        if ($this->isCsrfTokenValid('delete'.$enchere->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($enchere);
            $entityManager->flush();
        }

        return $this->redirectToRoute('enchere_index');
    }
}

templates/enchere/_delete_form.html.twig
<form method="post" action="{{ path('enchere_delete', {'id': enchere.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ enchere.id) }}">
    <button class="btn">Delete</button>
</form>

templates/enchere/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/enchere/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Enchere{% endblock %}

{% block body %}
    <h1>Edit Enchere</h1>

    {{ include('enchere/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('enchere_index') }}">back to list</a>

    {{ include('enchere/_delete_form.html.twig') }}
{% endblock %}

templates/enchere/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Enchere index{% endblock %}

{% block body %}
    <h1>Enchere index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Auction_value</th>
                <th>CreatedAt</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for enchere in encheres %}
            <tr>
                <td>{{ enchere.id }}</td>
                <td>{{ enchere.auctionValue }}</td>
                <td>{{ enchere.createdAt ? enchere.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('enchere_show', {'id': enchere.id}) }}">show</a>
                    <a href="{{ path('enchere_edit', {'id': enchere.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('enchere_new') }}">Create new</a>
{% endblock %}

templates/enchere/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Enchere{% endblock %}

{% block body %}
    <h1>Create new Enchere</h1>

    {{ include('enchere/_form.html.twig') }}

    <a href="{{ path('enchere_index') }}">back to list</a>
{% endblock %}

templates/enchere/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Enchere{% endblock %}

{% block body %}
    <h1>Enchere</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ enchere.id }}</td>
            </tr>
            <tr>
                <th>Auction_value</th>
                <td>{{ enchere.auctionValue }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ enchere.createdAt ? enchere.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('enchere_index') }}">back to list</a>

    <a href="{{ path('enchere_edit', {'id': enchere.id}) }}">edit</a>

    {{ include('enchere/_delete_form.html.twig') }}
{% endblock %}